kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: /backend-nonprod/us-west-2/kubernetes/argocdapp/helm-secrets
type: Opaque
stringData:
  sample-secret: <foo>
