kind: Secret
apiVersion: v1
data:
  AVP_TYPE: awssecretsmanager
metadata:
  name: example-secret
  namespace: argo-cd
  annotations:
    avp.kubernetes.io/path: "backend-nonprod/us-west-2/kubernetes/argocdapp/helm-secrets"
type: Opaque
stringData:
  sample-secret: <foo | base64encode>
